/*********************************************************************
** ---------------------- Copyright notice ---------------------------
** This source code is part of the EVASoft project
** It is property of Alain Boute Ingenierie - www.abing.fr and is
** distributed under the GNU Public Licence version 2
** Commercial use is submited to licencing - contact eva@abing.fr
** -------------------------------------------------------------------
**        File : README.MD
** Description : basic informations on the EVA project
**      Author : Alain BOUTE
**     Created : Jul 4 2018
*********************************************************************/

The EVA project offers a development & production environment for software applications based on the web standards : HTML, javascript and CSS

The project holds the following folders :
	src : C source code for the cgi, DLL & webservice executables
	include : C source includes for the cgi, DLL & webservice executables
	js : javascript code for HTML pages generated by the cgi executable
	VC6 : project & definition files to compile the project with Microsoft Visual studio 6
	doc : general documentation
